title: Aulas Pedro Kroger
email: kroger@ufba.br
description: Aulas de Pedro Kroger
url: "https://pkroger.com"

exclude:
  - antigos
  - Makefile

markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Define the default layout for all pages and pages in "aulas"
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "aulas"
      type: "pages"
    values:
      layout: "aula"
