
semestre: 2024.1
title: Aulas
email: kroger@ufba.br
description: Aulas de Pedro Kroger
url: "https://pkroger.com"

exclude: [antigos, Makefile]

markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]